from __future__ import annotations

GROUNDING_CORPUS: dict[str, list[dict[str, object]]] = {
    "bangkok": [
        {
            "id": "bkk-1",
            "sourceName": "YouTube neighborhood food guide",
            "sourceType": "video",
            "url": "https://www.youtube.com/results?search_query=Bangkok+street+food+neighborhood+guide",
            "published": "2025-01-18",
            "trust": 0.82,
            "text": "Bangkok performs best when the itinerary is district-focused: Chinatown for late food density, Ari for calmer cafes, and Talad Noi for design and creative walks.",
            "tags": ["food", "nightlife", "local", "cafe", "walkable"],
            "entities": [
                "Chinatown late-night street food crawl",
                "Ari specialty cafe run",
                "Talad Noi creative quarter",
            ],
        },
        {
            "id": "bkk-2",
            "sourceName": "Reddit traveler discussion",
            "sourceType": "community",
            "url": "https://www.reddit.com/search/?q=Bangkok+itinerary+food+districts&type=link",
            "published": "2024-11-02",
            "trust": 0.76,
            "text": "Repeat traveler discussions favor river transit and BTS-linked plans because they reduce heat friction and keep market-to-dinner routing efficient.",
            "tags": ["transport", "budget", "food", "efficiency"],
            "entities": [
                "Wat Arun riverside circuit",
                "Bang Rak side-street eateries",
            ],
        },
        {
            "id": "bkk-3",
            "sourceName": "Destination operations note",
            "sourceType": "seeded",
            "url": "https://www.youtube.com/results?search_query=Bangkok+river+market+rooftop+guide",
            "published": "2025-02-04",
            "trust": 0.81,
            "text": "Bangkok gains score when value, food density, and nightlife optionality are balanced against heat and road-safety awareness.",
            "tags": ["budget", "food", "nightlife", "safety"],
            "entities": [
                "Grand Palace and Wat Phra Kaew",
                "Chinatown late-night street food crawl",
            ],
        },
    ],
    "tokyo": [
        {
            "id": "tko-1",
            "sourceName": "YouTube Tokyo district guide",
            "sourceType": "video",
            "url": "https://www.youtube.com/results?search_query=Tokyo+district+guide+food+walk",
            "published": "2025-02-11",
            "trust": 0.88,
            "text": "Tokyo rewards neighborhood clustering. Asakusa, Yanaka, Nakameguro, and Kiyosumi-Shirakawa repeatedly show up in high-quality route guides because they reduce transit churn while preserving food depth and local texture.",
            "tags": ["walkable", "culture", "food", "design", "safe"],
            "entities": [
                "Asakusa and Senso-ji",
                "Yanaka backstreets",
                "Nakameguro evening walk",
                "Kiyosumi-Shirakawa cafe pockets",
            ],
        },
        {
            "id": "tko-2",
            "sourceName": "Reddit Tokyo planning threads",
            "sourceType": "community",
            "url": "https://www.reddit.com/search/?q=Tokyo+itinerary+neighborhood+food+reddit&type=link",
            "published": "2024-12-19",
            "trust": 0.79,
            "text": "Community discussions consistently recommend pairing shrines, depachika lunches, and one atmosphere-heavy evening district rather than crossing the entire city multiple times in one day.",
            "tags": ["food", "culture", "logistics", "efficiency"],
            "entities": [
                "Asakusa and Senso-ji",
                "Depachika lunch circuit",
                "Shinjuku omakase or izakaya corridor",
            ],
        },
        {
            "id": "tko-3",
            "sourceName": "Safety and operations synthesis",
            "sourceType": "seeded",
            "url": "https://www.youtube.com/results?search_query=Tokyo+solo+travel+guide+safety",
            "published": "2025-01-07",
            "trust": 0.9,
            "text": "Tokyo scores strongly for solo and design-aware trips because safety, logistics reliability, and high-quality food options align unusually well.",
            "tags": ["safe", "solo", "design", "food"],
            "entities": [
                "Kissaten breakfast and coffee stop",
                "teamLab and waterfront district",
            ],
        },
    ],
    "bali": [
        {
            "id": "bli-1",
            "sourceName": "YouTube Bali zone planning guide",
            "sourceType": "video",
            "url": "https://www.youtube.com/results?search_query=Bali+zone+planning+guide+Ubud+Canggu+Uluwatu",
            "published": "2025-01-23",
            "trust": 0.84,
            "text": "The strongest Bali itineraries choose one zone per day: Ubud for temples and terraces, Canggu for cafe culture, and Uluwatu for sunset payoff.",
            "tags": ["scenic", "wellness", "cafe", "sunset"],
            "entities": [
                "Ubud terraces and temple circuit",
                "Canggu specialty cafe run",
                "Uluwatu cliffs and sunset route",
            ],
        },
        {
            "id": "bli-2",
            "sourceName": "Reddit Bali route discussion",
            "sourceType": "community",
            "url": "https://www.reddit.com/search/?q=Bali+Ubud+Canggu+itinerary+reddit&type=link",
            "published": "2024-10-28",
            "trust": 0.74,
            "text": "Traveler threads repeatedly warn against overloading Bali with long same-day transfers. Private driver days and sunrise-sunset anchors perform better than aggressive route plans.",
            "tags": ["transport", "wellness", "scenic", "efficiency"],
            "entities": [
                "Quiet beach sunrise window",
                "Cliffside or beach-view dinner",
            ],
        },
        {
            "id": "bli-3",
            "sourceName": "Lifestyle signal synthesis",
            "sourceType": "seeded",
            "url": "https://www.youtube.com/results?search_query=Bali+cafe+wellness+travel+guide",
            "published": "2025-02-14",
            "trust": 0.8,
            "text": "Bali ranks highly when the trip brief values scenic pacing, cafe exploration, wellness tone, and one emotionally strong sunset moment.",
            "tags": ["wellness", "cafe", "lifestyle", "scenic"],
            "entities": [
                "Pererenan village cafe pocket",
                "Cliffside or beach-view dinner",
            ],
        },
    ],
    "dubai": [
        {
            "id": "dxb-1",
            "sourceName": "YouTube Dubai skyline guide",
            "sourceType": "video",
            "url": "https://www.youtube.com/results?search_query=Dubai+skyline+guide+desert+itinerary",
            "published": "2025-01-12",
            "trust": 0.83,
            "text": "Dubai performs best when skyline icons, desert experiences, and climate-controlled daytime anchors are mixed intentionally instead of treated as one continuous city walk.",
            "tags": ["premium", "iconic", "climate", "scenic"],
            "entities": [
                "Burj Khalifa and Downtown Dubai",
                "Dubai Marina night circuit",
            ],
        },
        {
            "id": "dxb-2",
            "sourceName": "Reddit Dubai comfort planning",
            "sourceType": "community",
            "url": "https://www.reddit.com/search/?q=Dubai+itinerary+metro+desert+reddit&type=link",
            "published": "2024-11-11",
            "trust": 0.75,
            "text": "Community planning threads emphasize metro-linked districts for value and warn that heat makes over-ambitious outdoor routing inefficient for much of the year.",
            "tags": ["transport", "premium", "budget", "climate"],
            "entities": [
                "Alserkal Avenue creative district",
                "Metro-linked districts",
            ],
        },
        {
            "id": "dxb-3",
            "sourceName": "Hospitality signal synthesis",
            "sourceType": "seeded",
            "url": "https://www.youtube.com/results?search_query=Dubai+luxury+stay+food+guide",
            "published": "2025-02-02",
            "trust": 0.86,
            "text": "Dubai stays strongest for premium-comfort briefs where hospitality polish matters as much as pure local texture.",
            "tags": ["premium", "luxury", "food", "comfort"],
            "entities": [
                "Rooftop dinner skyline arc",
                "Dubai Marina night circuit",
            ],
        },
    ],
    "singapore": [
        {
            "id": "sgp-1",
            "sourceName": "YouTube Singapore food-city guide",
            "sourceType": "video",
            "url": "https://www.youtube.com/results?search_query=Singapore+food+city+guide+hawker+districts",
            "published": "2025-01-29",
            "trust": 0.87,
            "text": "Singapore repeatedly scores well in food-city guides because hawker anchors, MRT efficiency, and waterfront evenings combine into low-friction premium-feeling short trips.",
            "tags": ["food", "safe", "efficient", "short-trip"],
            "entities": [
                "Gardens by the Bay",
                "Tiong Bahru cafe and bakery circuit",
                "Hawker center tasting route",
            ],
        },
        {
            "id": "sgp-2",
            "sourceName": "Reddit Singapore neighborhood threads",
            "sourceType": "community",
            "url": "https://www.reddit.com/search/?q=Singapore+Tiong+Bahru+Joo+Chiat+reddit&type=link",
            "published": "2024-12-07",
            "trust": 0.78,
            "text": "Repeat visitor discussions point toward pairing icon districts with one neighborhood district such as Tiong Bahru or Joo Chiat to avoid a flat checklist experience.",
            "tags": ["food", "neighborhood", "safe", "design"],
            "entities": [
                "Tiong Bahru cafe and bakery circuit",
                "Joo Chiat local texture route",
            ],
        },
        {
            "id": "sgp-3",
            "sourceName": "Urban trust synthesis",
            "sourceType": "seeded",
            "url": "https://www.youtube.com/results?search_query=Singapore+safe+short+trip+guide",
            "published": "2025-02-16",
            "trust": 0.91,
            "text": "Singapore is strongest for short, safety-first, food-led urban exploration where trust in logistics matters more than deep nightlife variety.",
            "tags": ["safe", "food", "efficient", "urban"],
            "entities": [
                "Gardens by the Bay",
                "Marina Bay evening walk",
            ],
        },
    ],
    "paris": [
        {
            "id": "prs-1",
            "sourceName": "YouTube Paris district guide",
            "sourceType": "video",
            "url": "https://www.youtube.com/results?search_query=Paris+district+guide+cafes+walk",
            "published": "2025-01-15",
            "trust": 0.84,
            "text": "Paris feels strongest when days are district-led: one cultural anchor, one cafe ritual, and one river or neighborhood walk rather than aggressive cross-city scheduling.",
            "tags": ["culture", "cafe", "walkable", "atmosphere"],
            "entities": [
                "Louvre or Musee d'Orsay anchor block",
                "Canal Saint-Martin cafe wander",
                "Le Marais local walk",
            ],
        },
        {
            "id": "prs-2",
            "sourceName": "Reddit Paris pacing threads",
            "sourceType": "community",
            "url": "https://www.reddit.com/search/?q=Paris+district+itinerary+reddit&type=link",
            "published": "2024-10-05",
            "trust": 0.77,
            "text": "Community advice repeatedly favors slower pacing, district clustering, and reserving one standout bistro or museum instead of trying to optimize every hour.",
            "tags": ["culture", "walkable", "pace", "food"],
            "entities": [
                "Classic bistro dinner block",
                "Le Marais local walk",
            ],
        },
        {
            "id": "prs-3",
            "sourceName": "Atmosphere synthesis",
            "sourceType": "seeded",
            "url": "https://www.youtube.com/results?search_query=Paris+cafe+culture+walkable+trip",
            "published": "2025-02-08",
            "trust": 0.83,
            "text": "Paris wins when the brief values atmosphere, culture, and cafe rhythm more than operational efficiency.",
            "tags": ["culture", "cafe", "atmosphere", "walkable"],
            "entities": [
                "Canal Saint-Martin cafe wander",
                "Louvre or Musee d'Orsay anchor block",
            ],
        },
    ],
    "goa": [
        {
            "id": "goa-1",
            "sourceName": "YouTube Goa north-south guide",
            "sourceType": "video",
            "url": "https://www.youtube.com/results?search_query=Goa+north+south+guide+beach+cafes",
            "published": "2025-01-09",
            "trust": 0.8,
            "text": "Goa route quality improves when north and south clusters are treated separately. Sunset blocks, cafe pockets, and one evening social arc create the strongest trip memory.",
            "tags": ["beach", "cafe", "nightlife", "scenic"],
            "entities": [
                "Fontainhas and Latin quarter walk",
                "Assagao cafe and design lane",
                "Sunset beach dinner arc",
            ],
        },
        {
            "id": "goa-2",
            "sourceName": "Reddit Goa district discussion",
            "sourceType": "community",
            "url": "https://www.reddit.com/search/?q=Goa+Assagao+Mandrem+itinerary+reddit&type=link",
            "published": "2024-11-21",
            "trust": 0.73,
            "text": "Discussion threads consistently recommend deciding between relaxed coastal rhythm and nightlife-heavy movement before choosing the daily route.",
            "tags": ["beach", "nightlife", "pace", "local"],
            "entities": [
                "Assagao cafe and design lane",
                "Quiet beach sunrise window",
            ],
        },
        {
            "id": "goa-3",
            "sourceName": "Lifestyle route synthesis",
            "sourceType": "seeded",
            "url": "https://www.youtube.com/results?search_query=Goa+beach+nightlife+cafe+guide",
            "published": "2025-02-06",
            "trust": 0.79,
            "text": "Goa is strongest for lifestyle travel where beach pacing, cafe culture, and optional nightlife matter more than dense urban sightseeing.",
            "tags": ["beach", "lifestyle", "nightlife", "cafe"],
            "entities": [
                "Sunset beach dinner arc",
                "Assagao cafe and design lane",
            ],
        },
    ],
    "fallback": [
        {
            "id": "fb-1",
            "sourceName": "Generic city-break synthesis",
            "sourceType": "seeded",
            "url": "https://www.youtube.com/results?search_query=city+break+walkable+food+guide",
            "published": "2025-01-01",
            "trust": 0.7,
            "text": "Fallback travel planning performs best when one district is used as the daily anchor and food, culture, and scenic blocks are clustered around it.",
            "tags": ["walkable", "food", "culture", "fallback"],
            "entities": [],
        }
    ],
}
